/// Multi-language localization for the app.
/// Supports English, Chinese, Malay, Tamil.
class AppLocalizations {
  final String languageCode;

  AppLocalizations(this.languageCode);

  static final Map<String, Map<String, String>> _values = {
    'en': {
      // Home Screen
      'appTitle': 'Visual Assistant',
      'welcome': 'Welcome to Visual Assistant',
      'chooseFeature': 'Choose a feature to get started',
      'obstacleDetection': 'Obstacle Detection',
      'chatbot': 'AI Chatbot',
      'visionAwareness': 'Vision Awareness',
      'settings': 'Settings',
      'signOut': 'Sign Out',

      // Settings
      'settingsTitle': 'Settings',
      'language': 'Language',
      'colorTheme': 'Color Theme',
      'textSize': 'Text Size',
      'ttsSpeed': 'Speech Speed',
      'scale': 'Scale',
      'speed': 'Speed',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'highContrast': 'High Contrast',
      'back': 'Back',

      // Accessibility
      'hapticFeedback': 'Haptic Feedback',
      'speechToText': 'Speech to Text',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'resetDefaults': 'Reset to Defaults',
      'resetConfirm': 'All settings have been reset.',

      // Chat Screen
      'chatTitle': 'Visual Assistant',
      'settingsAndHistory': 'Settings & History',
      'ttsLabel': 'Text-to-Speech',
      'ttsEnabledDesc': 'AI responses will be spoken',
      'ttsSilentMode': 'Silent mode',
      'ttsEnabled': 'Text-to-Speech enabled',
      'ttsStopped': 'Text-to-Speech stopped',
      'toggleTts': 'Toggle Text-to-Speech',
      'liveMode': 'Live',
      'normalMode': 'Normal',
      'shareConversation': 'Share Conversation',
      'exportAsText': 'Export as text',
      'clearCurrentChat': 'Clear Current Chat',
      'chatHistory': 'Chat History (3 days)',
      'noConversations': 'No conversations yet',
      'noMatchingConversations': 'No matching conversations',
      'noMessagesToExport': 'No messages to export',
      'typeMessage': 'Type message...',
      'addMessageAboutImage': 'Add a message about the image...',
      'sendMessage': 'Send Message',
      'takePicture': 'Take Picture',
      'chooseFromGallery': 'Choose from Gallery',
      'darkThemeActive': 'Dark theme active',
      'lightThemeActive': 'Light theme active',
      'liveSessionConnected':
          'Live session connected. Tap the microphone to start speaking.',
      'liveSessionFailed': 'Failed to connect live session',
      'liveSessionDisconnected': 'Live session disconnected.',
      'liveSessionError': 'Error in live session',
      'liveSessionNotConnected': 'Live session not connected',
      'waitForAI': 'Wait for AI to finish speaking',
      'refresh': 'Refresh',
      'messages': 'messages',
      'newConversation': 'New conversation',
      'today': 'Today',

      // Obstacle Detector Screen
      'cameraPermissionRequired': 'Camera Permission Required',
      'cameraPermissionDesc':
          'This app needs camera access to detect obstacles.',
      'openSettings': 'Open Settings',
      'pause': 'PAUSE',
      'resume': 'RESUME',
      'pauseDetection': 'Pause detection',
      'resumeDetection': 'Resume detection',
      'describe': 'DESCRIBE',
      'describeScene': 'Describe scene',
      'depthTestReady': 'DEPTH TEST (Ready)',
      'depthTestNotLoaded': 'DEPTH TEST (Not Loaded)',
      'depthTest': 'Test depth estimation',
      'startLiveAssistant': 'START LIVE ASSISTANT',
      'endLive': 'END LIVE',
      'live': 'LIVE',
      'navigate': 'NAVIGATE',
      'navigateButton': 'Open navigation',
      'realtimeDetection': 'Real-time detection',
      'detectionActive': 'Detection active',
      'detectionPaused': 'Detection paused',
      'obstacle': 'obstacle',
      'obstacles': 'obstacles',
      'labels': 'Labels:',
      'text': 'Text:',

      // Navigation Screen
      'accessibleNavigation': 'Accessible Navigation',
      'searchDestination': 'Search destination...',
      'search': 'Search',
      'exploreMode': 'Explore Mode - Auto-announce nearby',
      'exploringMode': 'Explore Mode',
      'stop': 'Stop',
      'stopNavigation': 'Stop navigation',
      'retry': 'Retry',
      'startNavigateTo': 'Start navigation to',
      'repeat': 'Repeat',
      'nextStep': 'Next',
      'arrived': 'Arrived',
      'confirm': 'OK',
      'cancel': 'Cancel',
      'nearbyPlaces': 'Nearby places found',
      'locationPermissionRequired': 'Location permission required',
      'locationPermissionDesc':
          'Please enable location permission in settings to use navigation',
      'locationPermissionDenied': 'Location permission denied',
      'locationPermissionPermanentlyDenied':
          'Location permission permanently denied, please enable in settings',
      'gettingLocation': 'Getting location...',
      'cannotGetLocation': 'Cannot get current location',
      'checkLocationService': 'Please check if location service is enabled',
      'navigationStopped': 'Navigation stopped',
      'navigationOpened':
          'Navigation opened. Enter a destination or start explore mode.',
      'requestingPermission': 'Requesting location permission',
      'permissionGranted': 'Location permission granted',
      'searching': 'Searching',
      'noResults': 'No results found',
      'foundResults': 'Found results',
      'selected': 'Selected',
      'gettingRoute': 'Getting route.',

      // Awareness Screen
      'awarenessMenu': 'Awareness Menu',
      'visionSimulator': 'Vision Simulator',
      'sightFacts': 'Sight Facts',
      'openVisionSimulator': 'Open vision simulator',
      'openSightFacts': 'Open sight facts',

      // Vision Simulator Screen
      'normal': 'NORMAL',
      'slide': 'SLIDE',
      'glaucoma': 'Glaucoma',
      'cataracts': 'Cataracts',
      'retinopathy': 'Retinopathy',
      'selectGlaucoma': 'Select Glaucoma mode',
      'selectCataracts': 'Select Cataracts mode',
      'selectRetinopathy': 'Select Retinopathy mode',
      'dragToCompare': 'Drag slider to compare normal and impaired vision',

      // Sight Facts Screen
      'sightFactsTitle': 'Sight Facts',
      'nationalSupport': 'National Support (NCBM)',
      'openNationalSupport':
          'Open National Council for the Blind Malaysia website',
      'factOf': 'of',
      'fact1Title': 'The Silent Thief',
      'fact1Content':
          "Glaucoma is often called the 'silent thief of sight' because it gradually steals vision without any early symptoms or pain.",
      'fact2Title': 'Tunnel Vision',
      'fact2Content':
          "Advanced Glaucoma typically results in 'tunnel vision', where you lose your side (peripheral) vision first.",
      'fact3Title': 'Regular Checks',
      'fact3Content':
          'Vision lost to Glaucoma cannot be recovered. Regular eye exams are the only way to catch it early and stop it.',
      'fact4Title': 'Inclusive Design',
      'fact4Content':
          'High contrast buttons (like in this app!) help people with low vision distinguish elements easier.',

      // Login Screen
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'confirmPassword': 'Confirm Password',
      'fullName': 'Full Name',
      'phoneNumber': 'Phone Number',
      'emergencyContactName': 'Emergency Contact Name',
      'emergencyContactPhone': 'Emergency Contact Phone',
      'forgotPassword': 'Forgot Password?',
      'signInWithGoogle': 'Sign in with Google',
      'orSignInWith': 'Or sign in with',
      'dontHaveAccount': "Don't have an account?",
      'alreadyHaveAccount': 'Already have an account?',
      'registerNow': 'Register Now',
      'loginNow': 'Login Now',
      'sendResetEmail': 'Send Reset Email',
      'backToLogin': 'Back to Login',
      'resetPasswordTitle': 'Reset Password',
      'resetPasswordDesc': 'Enter your email to receive a password reset link.',
      'verifyEmail': 'Verify Your Email',
      'verifyEmailDesc':
          'A verification email has been sent. Please check your inbox and verify your email.',
      'resendEmail': 'Resend Email',
      'checkVerification': 'I have verified',
      'personalInfo': 'Personal Information',
      'emergencyContact': 'Emergency Contact',
      'accountInfo': 'Account Information',

      // Emergency / Fall Detection
      'fallDetected': 'FALL DETECTED!',
      'callingAssistance': 'Calling assistance in:',
      'imOkay': "I'M OKAY",
      'cancelAlarm': '(Cancel Alarm)',
      'imOkayButton': 'I am okay, cancel emergency alarm',

      // Additional Login Keys
      'signIn': 'Sign In',
      'createAccount': 'Create Account',
      'dontHaveAccountRegister': "Don't have an account? Register here",
      'forgotPasswordResetHere': 'Forgot Password? Reset Here',
      'continueWithGoogle': 'Continue with Google',
      'or': 'OR',
      'createYourAccount': 'Create Your Account',
      'fillInDetails': 'Fill in your details to get started',
      'setPassword': 'Set Password',
      'passwordHint': 'Min 6 chars, 1 uppercase, 1 number',
      'emergencyContactDesc':
          'This person will be contacted in case of emergencies detected by the app.',
      'alreadyHaveAccountSignIn': 'Already have an account? Sign in here',
      'verificationEmailSent': 'Verification email sent! Check your inbox.',
      'checkYourEmail': 'Check Your Email',
      'verificationLinkSent': 'We sent a verification link to',
      'clickLinkToVerify':
          'Please click the link in the email to verify your account.',
      'iveVerifiedMyEmail': "I've Verified My Email",
      'resendVerificationEmail': 'Resend Verification Email',
      'emailNotVerified':
          'Email not verified yet. Check your inbox and click the link.',
      'resetLinkSent': 'Reset Link Sent!',
      'resetLinkSentDesc':
          'Please check your inbox and click the link to reset your password.',
      'tryDifferentEmail': 'Try a Different Email',
      'forgotYourPassword': 'Forgot Your Password?',
      'forgotYourPasswordDesc':
          "Enter the email address associated with your account and we'll send you a link to reset your password.",
      'sendResetLink': 'Send Reset Link',
      'emailAddress': 'Email Address',
      'normalVision': 'NORMAL',
      'emailHint': 'e.g. john@example.com',
      'nameHint': 'e.g. John Doe',
      'phoneHint': 'e.g. +60123456789',
      'fullNameRequired': 'Full Name *',
      'emailRequired': 'Email Address *',
      // Profile Feature
      'profileTitle': 'User Profile',
      'openingProfile': 'Opening user profile',
      'updateProfile': 'Save Changes',
      'profileUpdated': 'Profile updated successfully!',
      'updateFailed': 'Failed to update profile',
      'phoneRequired': 'Phone Number *',
      'passwordRequired': 'Password *',
      'confirmPasswordRequired': 'Confirm Password *',
      'emergencyContactNameRequired': 'Emergency Contact Name *',
      'emergencyContactPhoneRequired': 'Emergency Contact Phone *',
      'emergencyPhoneHint': 'e.g. +60198765432',
      'verificationResent': 'Verification email resent! Check your inbox.',
      'weSentResetLink': 'We sent a password reset link to',

      // Obstacle Detector Hub
      'obstacleDetectorHub': 'Obstacle Detector',
      'chooseAFeature': 'Choose a feature',
      'objectDetection': 'OBJECT DETECTION',
      'objectDetectionSubtitle':
          'Detect obstacles with camera & haptic feedback',
      'objectDetectionSemantic':
          'Object Detection. Detect obstacles using camera with haptic and voice feedback.',
      'openingObjectDetection': 'Opening object detection',
      'liveAssistant': 'LIVE',
      'liveAssistantSubtitle': 'Real-time AI assistant with voice & camera',
      'liveAssistantSemantic':
          'Live Assistant. Start a real-time conversation with Gemini AI using voice and camera.',
      'openingLiveAssistant': 'Opening live assistant',
      'liveTest': 'LIVE TEST',
      'liveTestSubtitle': 'Debug Live API step by step',
      'liveTestSemantic': 'Live Test. Debug the Gemini Live API step by step.',
      'openingLiveTest': 'Opening live test',
      'navigateSubtitle': 'Voice-guided walking directions',
      'navigateSemantic':
          'Navigate. Get voice-guided walking directions to a destination.',
      'openingNavigation': 'Opening navigation',
      'goBackHome': 'Go back to home screen',
      'obstacleDetectorMenuTts':
          'Obstacle detector menu. Three options available: Object Detection, Live Assistant, and Navigation.',

      // Feature & Settings TTS
      'usingLanguage': 'You are using English',
      'usingDarkMode': 'Using dark mode',
      'usingLightMode': 'Using light mode',
      'textSizeChanged': 'Text size changed to ',
      'speechSpeedChanged': 'Speech speed changed to ',
      'hapticEnabled': 'Haptic feedback enabled',
      'hapticDisabled': 'Haptic feedback disabled',
      'voiceGuidance': 'Voice Guidance',
      'voiceGuidanceEnabled': 'Voice Guidance is enabled',
      'voiceGuidanceDisabled': 'Voice Guidance is disabled',
      'openingChatbot': 'Opening AI chatbot',
      'openingVisionAwareness': 'Opening vision awareness',
      'openingSettings': 'Opening settings',
      'openingObstacleDetection': 'Opening obstacle detection',
    },
    'zh': {
      // Home Screen
      'appTitle': '视觉助手',
      'welcome': '欢迎使用视觉助手',
      'chooseFeature': '选择一个功能开始',
      'obstacleDetection': '障碍物检测',
      'chatbot': 'AI 聊天机器人',
      'visionAwareness': '视觉意识',
      'settings': '设置',
      'signOut': '退出登录',
      'settingsTitle': '设置',
      'language': '语言',
      'colorTheme': '颜色主题',
      'textSize': '文字大小',
      'ttsSpeed': '语速',
      'scale': '缩放',
      'speed': '速度',
      'lightMode': '浅色模式',
      'darkMode': '深色模式',
      'highContrast': '高对比度',
      'back': '返回',
      'hapticFeedback': '触觉反馈',
      'speechToText': '语音转文字',
      'enabled': '已开启',
      'disabled': '已关闭',
      'resetDefaults': '恢复默认设置',
      'resetConfirm': '所有设置已重置。',

      // Chat Screen
      'chatTitle': '视觉助手',
      'settingsAndHistory': '设置与历史',
      'ttsLabel': '文字转语音',
      'ttsEnabledDesc': 'AI 回复将被朗读',
      'ttsSilentMode': '静音模式',
      'ttsEnabled': '文字转语音已开启',
      'ttsStopped': '文字转语音已停止',
      'toggleTts': '切换文字转语音',
      'liveMode': '实时',
      'normalMode': '普通',
      'shareConversation': '分享对话',
      'exportAsText': '导出为文本',
      'clearCurrentChat': '清除当前对话',
      'chatHistory': '聊天历史 (3天)',
      'noConversations': '暂无对话',
      'noMatchingConversations': '没有匹配的对话',
      'noMessagesToExport': '没有消息可导出',
      'typeMessage': '输入消息...',
      'addMessageAboutImage': '添加关于图片的消息...',
      'sendMessage': '发送消息',
      'takePicture': '拍照',
      'chooseFromGallery': '从相册选择',
      'darkThemeActive': '深色主题已启用',
      'lightThemeActive': '浅色主题已启用',
      'liveSessionConnected': '🎙️ 实时会话已连接。点击麦克风开始说话。',
      'liveSessionFailed': '❌ 连接实时会话失败',
      'liveSessionDisconnected': '🔌 实时会话已断开。',
      'liveSessionError': '❌ 实时会话错误',
      'liveSessionNotConnected': '实时会话未连接',
      'waitForAI': '请等待 AI 说完',
      'refresh': '刷新',
      'messages': '条消息',
      'newConversation': '新对话',
      'today': '今天',

      // Obstacle Detector Screen
      'cameraPermissionRequired': '需要相机权限',
      'cameraPermissionDesc': '此应用需要相机权限来检测障碍物。',
      'openSettings': '打开设置',
      'pause': '暂停',
      'resume': '继续',
      'pauseDetection': '暂停检测',
      'resumeDetection': '继续检测',
      'describe': '描述',
      'describeScene': '描述场景',
      'depthTestReady': '深度测试（就绪）',
      'depthTestNotLoaded': '深度测试（未加载）',
      'depthTest': '测试深度估计',
      'startLiveAssistant': '开启实时助手',
      'endLive': '结束实时',
      'live': '实时',
      'navigate': '导航',
      'navigateButton': '打开导航',
      'realtimeDetection': '实时检测中',
      'detectionActive': '检测进行中',
      'detectionPaused': '检测已暂停',
      'obstacle': '个障碍物',
      'obstacles': '个障碍物',
      'labels': '标签：',
      'text': '文字：',

      // Navigation Screen
      'accessibleNavigation': '无障碍导航',
      'searchDestination': '搜索目的地...',
      'search': '搜索',
      'exploreMode': '开启探索模式 - 自动播报周边环境',
      'exploringMode': '探索模式',
      'stop': '停止',
      'stopNavigation': '停止导航',
      'retry': '重试',
      'startNavigateTo': '开始导航到',
      'repeat': '重复',
      'nextStep': '下一步',
      'arrived': '已到达',
      'confirm': '确定',
      'cancel': '取消',
      'nearbyPlaces': '附近发现的地点',
      'locationPermissionRequired': '需要位置权限',
      'locationPermissionDesc': '请在设置中开启位置权限以使用导航功能',
      'locationPermissionDenied': '位置权限被拒绝，导航功能无法使用',
      'locationPermissionPermanentlyDenied': '位置权限被永久拒绝，请在设置中开启',
      'gettingLocation': '正在获取位置...',
      'cannotGetLocation': '无法获取当前位置',
      'checkLocationService': '请检查位置服务是否已开启',
      'navigationStopped': '导航已停止',
      'navigationOpened': '导航界面已打开。请输入目的地或开启探索模式。',
      'requestingPermission': '正在请求位置权限',
      'permissionGranted': '位置权限已授予',
      'searching': '正在搜索',
      'noResults': '未找到结果',
      'foundResults': '找到结果',
      'selected': '已选择',
      'gettingRoute': '正在获取路线。',

      // Awareness Screen
      'awarenessMenu': '意识菜单',
      'visionSimulator': '视觉模拟器',
      'sightFacts': '视觉知识',
      'openVisionSimulator': '打开视觉模拟器',
      'openSightFacts': '打开视觉知识',

      // Vision Simulator Screen
      'normal': '正常',
      'slide': '滑动',
      'glaucoma': '青光眼',
      'cataracts': '白内障',
      'retinopathy': '视网膜病变',
      'selectGlaucoma': '选择青光眼模式',
      'selectCataracts': '选择白内障模式',
      'selectRetinopathy': '选择视网膜病变模式',
      'dragToCompare': '拖动滑块比较正常视觉和受损视觉',

      // Sight Facts Screen
      'sightFactsTitle': '视觉知识',
      'nationalSupport': '全国支持 (NCBM)',
      'openNationalSupport': '打开马来西亚全国盲人协会网站',
      'factOf': '/',
      'fact1Title': '无声的窃贼',
      'fact1Content': '青光眼通常被称为"视力的无声窃贼"，因为它在没有任何早期症状或疼痛的情况下逐渐窃取视力。',
      'fact2Title': '管状视野',
      'fact2Content': '晚期青光眼通常会导致"管状视野"，首先失去周边视力。',
      'fact3Title': '定期检查',
      'fact3Content': '青光眼造成的视力损失无法恢复。定期眼科检查是早期发现和阻止它的唯一方法。',
      'fact4Title': '包容性设计',
      'fact4Content': '高对比度按钮（如本应用中的按钮！）帮助低视力人群更容易区分元素。',

      // Login Screen
      'login': '登录',
      'register': '注册',
      'email': '电子邮件',
      'password': '密码',
      'confirmPassword': '确认密码',
      'fullName': '全名',
      'phoneNumber': '电话号码',
      'emergencyContactName': '紧急联系人姓名',
      'emergencyContactPhone': '紧急联系人电话',
      'forgotPassword': '忘记密码？',
      'signInWithGoogle': '使用 Google 登录',
      'orSignInWith': '或使用以下方式登录',
      'dontHaveAccount': '还没有帐户？',
      'alreadyHaveAccount': '已有帐户？',
      'registerNow': '立即注册',
      'loginNow': '立即登录',
      'sendResetEmail': '发送重置邮件',
      'backToLogin': '返回登录',
      'resetPasswordTitle': '重置密码',
      'resetPasswordDesc': '输入您的电子邮件以接收密码重置链接。',
      'verifyEmail': '验证您的邮箱',
      'verifyEmailDesc': '验证邮件已发送。请检查收件箱并验证您的电子邮件。',
      'resendEmail': '重新发送',
      'checkVerification': '我已验证',
      'personalInfo': '个人信息',
      'emergencyContact': '紧急联系人',
      'accountInfo': '帐户信息',

      // Emergency / Fall Detection
      'fallDetected': '检测到跌倒！',
      'callingAssistance': '将在以下时间呼叫援助：',
      'imOkay': '我没事',
      'cancelAlarm': '（取消警报）',
      'imOkayButton': '我没事，取消紧急警报',

      // Additional Login Keys
      'signIn': '登录',
      'createAccount': '创建帐户',
      'dontHaveAccountRegister': '还没有帐户？在此注册',
      'forgotPasswordResetHere': '忘记密码？在此重置',
      'continueWithGoogle': '使用 Google 继续',
      'or': '或',
      'createYourAccount': '创建您的帐户',
      'fillInDetails': '填写您的信息以开始',
      'setPassword': '设置密码',
      'passwordHint': '至少6个字符，1个大写字母，1个数字',
      'emergencyContactDesc': '当应用检测到紧急情况时，将联系此人。',
      'alreadyHaveAccountSignIn': '已有帐户？在此登录',
      'verificationEmailSent': '验证邮件已发送！请检查收件箱。',
      'checkYourEmail': '检查您的邮箱',
      'verificationLinkSent': '我们已发送验证链接到',
      'clickLinkToVerify': '请点击邮件中的链接以验证您的帐户。',
      'iveVerifiedMyEmail': '我已验证邮箱',
      'resendVerificationEmail': '重新发送验证邮件',
      'emailNotVerified': '邮箱尚未验证。请检查收件箱并点击链接。',
      'resetLinkSent': '重置链接已发送！',
      'resetLinkSentDesc': '请检查收件箱并点击链接以重置密码。',
      'tryDifferentEmail': '尝试其他邮箱',
      'forgotYourPassword': '忘记密码？',
      'forgotYourPasswordDesc': '输入与您帐户关联的电子邮件，我们将向您发送密码重置链接。',
      'sendResetLink': '发送重置链接',
      'emailAddress': '电子邮件地址',
      'normalVision': '正常',
      'emailHint': '例如 john@example.com',
      'nameHint': '例如 张三',
      'phoneHint': '例如 +60123456789',
      'fullNameRequired': '全名 *',
      'emailRequired': '电子邮件地址 *',
      // Profile Feature
      'profileTitle': '用户个人资料',
      'openingProfile': '正在打开用户个人资料',
      'updateProfile': '保存更改',
      'profileUpdated': '个人资料更新成功！',
      'updateFailed': '更新个人资料失败',
      'phoneRequired': '电话 *',
      'passwordRequired': '密码 *',
      'confirmPasswordRequired': '确认密码 *',
      'emergencyContactNameRequired': '紧急联系人姓名 *',
      'emergencyContactPhoneRequired': '紧急联系人电话 *',
      'emergencyPhoneHint': '例如 +60198765432',
      'verificationResent': '验证邮件已重新发送！请检查收件箱。',
      'weSentResetLink': '我们已发送密码重置链接到',

      // Obstacle Detector Hub
      'obstacleDetectorHub': '障碍物检测器',
      'chooseAFeature': '选择一个功能',
      'objectDetection': '物体检测',
      'objectDetectionSubtitle': '使用摄像头和触觉反馈检测障碍物',
      'objectDetectionSemantic': '物体检测。使用摄像头和触觉及语音反馈检测障碍物。',
      'openingObjectDetection': '正在打开物体检测',
      'liveAssistant': '实时助手',
      'liveAssistantSubtitle': '使用语音和摄像头的实时 AI 助手',
      'liveAssistantSemantic': '实时助手。使用语音和摄像头与 Gemini AI 进行实时对话。',
      'openingLiveAssistant': '正在打开实时助手',
      'liveTest': '实时测试',
      'liveTestSubtitle': '逐步调试 Live API',
      'liveTestSemantic': '实时测试。逐步调试 Gemini Live API。',
      'openingLiveTest': '正在打开实时测试',
      'navigateSubtitle': '语音引导步行方向',
      'navigateSemantic': '导航。获取到达目的地的语音引导步行方向。',
      'openingNavigation': '正在打开导航',
      'goBackHome': '返回主屏幕',
      'obstacleDetectorMenuTts': '障碍物检测器菜单。三个可用选项：物体检测、实时助手和导航。',

      // Feature & Settings TTS
      'usingLanguage': '您正在使用中文',
      'usingDarkMode': '使用深色模式',
      'usingLightMode': '使用浅色模式',
      'textSizeChanged': '文字大小更改为 ',
      'speechSpeedChanged': '语速更改为 ',
      'hapticEnabled': '触觉反馈已开启',
      'hapticDisabled': '触觉反馈已关闭',
      'voiceGuidance': '语音引导',
      'voiceGuidanceEnabled': '语音引导已开启',
      'voiceGuidanceDisabled': '语音引导已关闭',
      'openingChatbot': '正在打开 AI 聊天机器人',
      'openingVisionAwareness': '正在打开视觉意识',
      'openingSettings': '正在打开设置',
      'openingObstacleDetection': '正在打开障碍物检测',
    },
    'ms': {
      // Home Screen
      'appTitle': 'Pembantu Visual',
      'welcome': 'Selamat datang ke Pembantu Visual',
      'chooseFeature': 'Pilih ciri untuk bermula',
      'obstacleDetection': 'Pengesanan Halangan',
      'chatbot': 'Chatbot AI',
      'visionAwareness': 'Kesedaran Penglihatan',
      'settings': 'Tetapan',
      'signOut': 'Log Keluar',
      'settingsTitle': 'Tetapan',
      'language': 'Bahasa',
      'colorTheme': 'Tema Warna',
      'textSize': 'Saiz Teks',
      'ttsSpeed': 'Kelajuan Pertuturan',
      'scale': 'Skala',
      'speed': 'Kelajuan',
      'lightMode': 'Mod Cerah',
      'darkMode': 'Mod Gelap',
      'highContrast': 'Kontras Tinggi',
      'back': 'Kembali',
      'hapticFeedback': 'Maklum Balas Sentuhan',
      'speechToText': 'Pertuturan ke Teks',
      'enabled': 'Diaktifkan',
      'disabled': 'Dilumpuhkan',
      'resetDefaults': 'Set Semula',
      'resetConfirm': 'Semua tetapan telah ditetapkan semula.',

      // Chat Screen
      'chatTitle': 'Pembantu Visual',
      'settingsAndHistory': 'Tetapan & Sejarah',
      'ttsLabel': 'Teks ke Pertuturan',
      'ttsEnabledDesc': 'Respons AI akan dibaca',
      'ttsSilentMode': 'Mod senyap',
      'ttsEnabled': 'Teks ke Pertuturan diaktifkan',
      'ttsStopped': 'Teks ke Pertuturan dihentikan',
      'toggleTts': 'Togol Teks ke Pertuturan',
      'liveMode': 'Langsung',
      'normalMode': 'Normal',
      'shareConversation': 'Kongsi Perbualan',
      'exportAsText': 'Eksport sebagai teks',
      'clearCurrentChat': 'Padam Chat Semasa',
      'chatHistory': 'Sejarah Chat (3 hari)',
      'noConversations': 'Tiada perbualan lagi',
      'noMatchingConversations': 'Tiada perbualan sepadan',
      'noMessagesToExport': 'Tiada mesej untuk dieksport',
      'typeMessage': 'Taip mesej...',
      'addMessageAboutImage': 'Tambah mesej tentang gambar...',
      'sendMessage': 'Hantar Mesej',
      'takePicture': 'Ambil Gambar',
      'chooseFromGallery': 'Pilih dari Galeri',
      'darkThemeActive': 'Tema gelap aktif',
      'lightThemeActive': 'Tema cerah aktif',
      'liveSessionConnected':
          '🎙️ Sesi langsung disambungkan. Ketik mikrofon untuk mula bercakap.',
      'liveSessionFailed': '❌ Gagal menyambung sesi langsung',
      'liveSessionDisconnected': '🔌 Sesi langsung diputuskan.',
      'liveSessionError': '❌ Ralat sesi langsung',
      'liveSessionNotConnected': 'Sesi langsung tidak disambungkan',
      'waitForAI': 'Tunggu AI selesai bercakap',
      'refresh': 'Muat semula',
      'messages': 'mesej',
      'newConversation': 'Perbualan baharu',
      'today': 'Hari ini',

      // Obstacle Detector Screen
      'cameraPermissionRequired': 'Kebenaran Kamera Diperlukan',
      'cameraPermissionDesc':
          'Apl ini memerlukan akses kamera untuk mengesan halangan.',
      'openSettings': 'Buka Tetapan',
      'pause': 'JEDA',
      'resume': 'TERUSKAN',
      'pauseDetection': 'Jeda pengesanan',
      'resumeDetection': 'Teruskan pengesanan',
      'describe': 'HURAIKAN',
      'describeScene': 'Huraikan pemandangan',
      'depthTestReady': 'UJIAN KEDALAMAN (Sedia)',
      'depthTestNotLoaded': 'UJIAN KEDALAMAN (Tidak Dimuatkan)',
      'depthTest': 'Ujian anggaran kedalaman',
      'startLiveAssistant': 'MULAKAN PEMBANTU LANGSUNG',
      'endLive': 'TAMAT LANGSUNG',
      'live': 'LANGSUNG',
      'navigate': 'NAVIGASI',
      'navigateButton': 'Buka navigasi',
      'realtimeDetection': 'Pengesanan masa nyata',
      'detectionActive': 'Pengesanan aktif',
      'detectionPaused': 'Pengesanan dijeda',
      'obstacle': 'halangan',
      'obstacles': 'halangan',
      'labels': 'Label:',
      'text': 'Teks:',

      // Navigation Screen
      'accessibleNavigation': 'Navigasi Mudah Akses',
      'searchDestination': 'Cari destinasi...',
      'search': 'Cari',
      'exploreMode': 'Mod Penerokaan - Umumkan persekitaran secara automatik',
      'exploringMode': 'Mod Penerokaan',
      'stop': 'Berhenti',
      'stopNavigation': 'Hentikan navigasi',
      'retry': 'Cuba semula',
      'startNavigateTo': 'Mula navigasi ke',
      'repeat': 'Ulang',
      'nextStep': 'Seterusnya',
      'arrived': 'Tiba',
      'confirm': 'OK',
      'cancel': 'Batal',
      'nearbyPlaces': 'Tempat berdekatan ditemui',
      'locationPermissionRequired': 'Kebenaran lokasi diperlukan',
      'locationPermissionDesc':
          'Sila aktifkan kebenaran lokasi dalam tetapan untuk menggunakan navigasi',
      'locationPermissionDenied': 'Kebenaran lokasi ditolak',
      'locationPermissionPermanentlyDenied':
          'Kebenaran lokasi ditolak secara kekal, sila aktifkan dalam tetapan',
      'gettingLocation': 'Mendapatkan lokasi...',
      'cannotGetLocation': 'Tidak dapat mendapatkan lokasi semasa',
      'checkLocationService': 'Sila semak jika perkhidmatan lokasi diaktifkan',
      'navigationStopped': 'Navigasi dihentikan',
      'navigationOpened':
          'Antara muka navigasi dibuka. Sila masukkan destinasi atau mulakan mod penerokaan.',
      'requestingPermission': 'Meminta kebenaran lokasi',
      'permissionGranted': 'Kebenaran lokasi diberikan',
      'searching': 'Mencari',
      'noResults': 'Tiada keputusan ditemui',
      'foundResults': 'Keputusan ditemui',
      'selected': 'Dipilih',
      'gettingRoute': 'Mendapatkan laluan.',

      // Awareness Screen
      'awarenessMenu': 'Menu Kesedaran',
      'visionSimulator': 'Simulator Penglihatan',
      'sightFacts': 'Fakta Penglihatan',
      'openVisionSimulator': 'Buka simulator penglihatan',
      'openSightFacts': 'Buka fakta penglihatan',

      // Vision Simulator Screen
      'normal': 'NORMAL',
      'slide': 'LUNCUR',
      'glaucoma': 'Glaukoma',
      'cataracts': 'Katarak',
      'retinopathy': 'Retinopati',
      'selectGlaucoma': 'Pilih mod Glaukoma',
      'selectCataracts': 'Pilih mod Katarak',
      'selectRetinopathy': 'Pilih mod Retinopati',
      'dragToCompare':
          'Seret peluncur untuk membanding penglihatan normal dan terjejas',

      // Sight Facts Screen
      'sightFactsTitle': 'Fakta Penglihatan',
      'nationalSupport': 'Sokongan Nasional (NCBM)',
      'openNationalSupport':
          'Buka laman web Majlis Kebangsaan bagi Orang Buta Malaysia',
      'factOf': 'daripada',
      'fact1Title': 'Pencuri Senyap',
      'fact1Content':
          "Glaukoma sering dipanggil 'pencuri senyap penglihatan' kerana ia secara beransur-ansur mencuri penglihatan tanpa sebarang gejala awal atau kesakitan.",
      'fact2Title': 'Penglihatan Terowong',
      'fact2Content':
          "Glaukoma lanjut biasanya mengakibatkan 'penglihatan terowong', di mana anda kehilangan penglihatan sisi (periferal) terlebih dahulu.",
      'fact3Title': 'Pemeriksaan Berkala',
      'fact3Content':
          'Penglihatan yang hilang akibat Glaukoma tidak boleh dipulihkan. Pemeriksaan mata berkala adalah satu-satunya cara untuk mengesannya awal dan menghentikannya.',
      'fact4Title': 'Reka Bentuk Inklusif',
      'fact4Content':
          'Butang kontras tinggi (seperti dalam aplikasi ini!) membantu orang yang kurang penglihatan membezakan elemen dengan lebih mudah.',

      // Login Screen
      'login': 'Log Masuk',
      'register': 'Daftar',
      'email': 'E-mel',
      'password': 'Kata Laluan',
      'confirmPassword': 'Sahkan Kata Laluan',
      'fullName': 'Nama Penuh',
      'phoneNumber': 'Nombor Telefon',
      'emergencyContactName': 'Nama Kenalan Kecemasan',
      'emergencyContactPhone': 'Telefon Kenalan Kecemasan',
      'forgotPassword': 'Lupa Kata Laluan?',
      'signInWithGoogle': 'Log masuk dengan Google',
      'orSignInWith': 'Atau log masuk dengan',
      'dontHaveAccount': 'Tiada akaun?',
      'alreadyHaveAccount': 'Sudah ada akaun?',
      'registerNow': 'Daftar Sekarang',
      'loginNow': 'Log Masuk Sekarang',
      'sendResetEmail': 'Hantar E-mel Set Semula',
      'backToLogin': 'Kembali ke Log Masuk',
      'resetPasswordTitle': 'Set Semula Kata Laluan',
      'resetPasswordDesc':
          'Masukkan e-mel anda untuk menerima pautan set semula kata laluan.',
      'verifyEmail': 'Sahkan E-mel Anda',
      'verifyEmailDesc':
          'E-mel pengesahan telah dihantar. Sila semak peti masuk anda dan sahkan e-mel anda.',
      'resendEmail': 'Hantar Semula',
      'checkVerification': 'Saya telah mengesahkan',
      'personalInfo': 'Maklumat Peribadi',
      'emergencyContact': 'Kenalan Kecemasan',
      'accountInfo': 'Maklumat Akaun',

      // Emergency / Fall Detection
      'fallDetected': 'JATUH DIKESAN!',
      'callingAssistance': 'Menghubungi bantuan dalam:',
      'imOkay': 'SAYA OK',
      'cancelAlarm': '(Batal Penggera)',
      'imOkayButton': 'Saya OK, batalkan penggera kecemasan',

      // Additional Login Keys
      'signIn': 'Log Masuk',
      'createAccount': 'Cipta Akaun',
      'dontHaveAccountRegister': 'Tiada akaun? Daftar di sini',
      'forgotPasswordResetHere': 'Lupa Kata Laluan? Set Semula Di Sini',
      'continueWithGoogle': 'Teruskan dengan Google',
      'or': 'ATAU',
      'createYourAccount': 'Cipta Akaun Anda',
      'fillInDetails': 'Isi butiran anda untuk bermula',
      'setPassword': 'Tetapkan Kata Laluan',
      'passwordHint': 'Min 6 aksara, 1 huruf besar, 1 nombor',
      'emergencyContactDesc':
          'Orang ini akan dihubungi sekiranya kecemasan dikesan oleh apl.',
      'alreadyHaveAccountSignIn': 'Sudah ada akaun? Log masuk di sini',
      'verificationEmailSent':
          'E-mel pengesahan dihantar! Semak peti masuk anda.',
      'checkYourEmail': 'Semak E-mel Anda',
      'verificationLinkSent': 'Kami telah menghantar pautan pengesahan ke',
      'clickLinkToVerify':
          'Sila klik pautan dalam e-mel untuk mengesahkan akaun anda.',
      'iveVerifiedMyEmail': 'Saya Telah Mengesahkan E-mel',
      'resendVerificationEmail': 'Hantar Semula E-mel Pengesahan',
      'emailNotVerified':
          'E-mel belum disahkan. Semak peti masuk dan klik pautan.',
      'resetLinkSent': 'Pautan Set Semula Dihantar!',
      'resetLinkSentDesc':
          'Sila semak peti masuk anda dan klik pautan untuk set semula kata laluan.',
      'tryDifferentEmail': 'Cuba E-mel Lain',
      'forgotYourPassword': 'Lupa Kata Laluan Anda?',
      'forgotYourPasswordDesc':
          'Masukkan alamat e-mel yang dikaitkan dengan akaun anda dan kami akan menghantar pautan untuk set semula kata laluan.',
      'sendResetLink': 'Hantar Pautan Set Semula',
      'emailAddress': 'Alamat E-mel',
      'normalVision': 'NORMAL',
      'emailHint': 'cth. john@example.com',
      'nameHint': 'cth. Ahmad Bin Ali',
      'phoneHint': 'cth. +60123456789',
      'fullNameRequired': 'Nama Penuh *',
      'emailRequired': 'Alamat E-mel *',
      // Profile Feature
      'profileTitle': 'Profil Pengguna',
      'openingProfile': 'Membuka profil pengguna',
      'updateProfile': 'Simpan Perubahan',
      'profileUpdated': 'Profil berjaya dikemas kini!',
      'updateFailed': 'Gagal mengemas kini profil',
      'phoneRequired': 'Nombor Telefon *',
      'passwordRequired': 'Kata Laluan *',
      'confirmPasswordRequired': 'Sahkan Kata Laluan *',
      'emergencyContactNameRequired': 'Nama Kenalan Kecemasan *',
      'emergencyContactPhoneRequired': 'Telefon Kenalan Kecemasan *',
      'emergencyPhoneHint': 'cth. +60198765432',
      'verificationResent':
          'E-mel pengesahan dihantar semula! Semak peti masuk anda.',
      'weSentResetLink':
          'Kami telah menghantar pautan set semula kata laluan ke',

      // Obstacle Detector Hub
      'obstacleDetectorHub': 'Pengesan Halangan',
      'chooseAFeature': 'Pilih satu ciri',
      'objectDetection': 'PENGESANAN OBJEK',
      'objectDetectionSubtitle':
          'Kesan halangan dengan kamera & maklum balas haptik',
      'objectDetectionSemantic':
          'Pengesanan Objek. Kesan halangan menggunakan kamera dengan maklum balas haptik dan suara.',
      'openingObjectDetection': 'Membuka pengesanan objek',
      'liveAssistant': 'LANGSUNG',
      'liveAssistantSubtitle': 'Pembantu AI masa nyata dengan suara & kamera',
      'liveAssistantSemantic':
          'Pembantu Langsung. Mulakan perbualan masa nyata dengan Gemini AI menggunakan suara dan kamera.',
      'openingLiveAssistant': 'Membuka pembantu langsung',
      'liveTest': 'UJIAN LANGSUNG',
      'liveTestSubtitle': 'Nyahpepijat API Langsung langkah demi langkah',
      'liveTestSemantic':
          'Ujian Langsung. Nyahpepijat API Gemini Live langkah demi langkah.',
      'openingLiveTest': 'Membuka ujian langsung',
      'navigateSubtitle': 'Arah berjalan dipandu suara',
      'navigateSemantic':
          'Navigasi. Dapatkan arah berjalan dipandu suara ke destinasi.',
      'openingNavigation': 'Membuka navigasi',
      'goBackHome': 'Kembali ke skrin utama',
      'obstacleDetectorMenuTts':
          'Menu pengesan halangan. Tiga pilihan tersedia: Pengesanan Objek, Pembantu Langsung, dan Navigasi.',

      // Feature & Settings TTS
      'usingLanguage': 'Anda sedang menggunakan bahasa Melayu',
      'usingDarkMode': 'Menggunakan mod gelap',
      'usingLightMode': 'Menggunakan mod cerah',
      'textSizeChanged': 'Saiz teks ditukar ke ',
      'speechSpeedChanged': 'Kelajuan pertuturan ditukar ke ',
      'hapticEnabled': 'Maklum balas sentuhan diaktifkan',
      'hapticDisabled': 'Maklum balas sentuhan dilumpuhkan',
      'voiceGuidance': 'Panduan Suara',
      'voiceGuidanceEnabled': 'Panduan bunyi telah dihidupkan',
      'voiceGuidanceDisabled': 'Panduan bunyi telah dimatikan',
      'openingChatbot': 'Membuka Chatbot AI',
      'openingVisionAwareness': 'Membuka kesedaran penglihatan',
      'openingSettings': 'Membuka tetapan',
      'openingObstacleDetection': 'Membuka pengesanan halangan',
    },
    'ta': {
      // Home Screen
      'appTitle': 'காட்சி உதவியாளர்',
      'welcome': 'காட்சி உதவியாளருக்கு வரவேற்கிறோம்',
      'chooseFeature': 'தொடங்க ஒரு அம்சத்தைத் தேர்ந்தெடுக்கவும்',
      'obstacleDetection': 'தடை கண்டறிதல்',
      'chatbot': 'AI அரட்டை',
      'visionAwareness': 'பார்வை விழிப்புணர்வு',
      'settings': 'அமைப்புகள்',
      'signOut': 'வெளியேறு',
      'settingsTitle': 'அமைப்புகள்',
      'language': 'மொழி',
      'colorTheme': 'வண்ண தீம்',
      'textSize': 'உரை அளவு',
      'ttsSpeed': 'பேச்சு வேகம்',
      'scale': 'அளவு',
      'speed': 'வேகம்',
      'lightMode': 'ஒளி பயன்முறை',
      'darkMode': 'இருண்ட பயன்முறை',
      'highContrast': 'உயர் மாறுபாடு',
      'back': 'திரும்ப',
      'hapticFeedback': 'தொடு பின்னூட்டம்',
      'speechToText': 'பேச்சிலிருந்து உரை',
      'enabled': 'இயக்கப்பட்டது',
      'disabled': 'முடக்கப்பட்டது',
      'resetDefaults': 'இயல்புநிலைக்கு மீட்டமை',
      'resetConfirm': 'அனைத்து அமைப்புகளும் மீட்டமைக்கப்பட்டன.',

      // Chat Screen
      'chatTitle': 'காட்சி உதவியாளர்',
      'settingsAndHistory': 'அமைப்புகள் & வரலாறு',
      'ttsLabel': 'உரையிலிருந்து பேச்சு',
      'ttsEnabledDesc': 'AI பதில்கள் படிக்கப்படும்',
      'ttsSilentMode': 'அமைதி பயன்முறை',
      'ttsEnabled': 'உரையிலிருந்து பேச்சு இயக்கப்பட்டது',
      'ttsStopped': 'உரையிலிருந்து பேச்சு நிறுத்தப்பட்டது',
      'toggleTts': 'உரையிலிருந்து பேச்சு மாற்று',
      'liveMode': 'நேரடி',
      'normalMode': 'சாதாரண',
      'shareConversation': 'உரையாடலைப் பகிர்',
      'exportAsText': 'உரையாக ஏற்றுமதி',
      'clearCurrentChat': 'தற்போதைய அரட்டையை அழி',
      'chatHistory': 'அரட்டை வரலாறு (3 நாட்கள்)',
      'noConversations': 'இன்னும் உரையாடல்கள் இல்லை',
      'noMatchingConversations': 'பொருத்தமான உரையாடல்கள் இல்லை',
      'noMessagesToExport': 'ஏற்றுமதி செய்ய செய்திகள் இல்லை',
      'typeMessage': 'செய்தி தட்டச்சு...',
      'addMessageAboutImage': 'படத்தைப் பற்றிய செய்தியைச் சேர்...',
      'sendMessage': 'செய்தி அனுப்பு',
      'takePicture': 'புகைப்படம் எடு',
      'chooseFromGallery': 'தொகுப்பிலிருந்து தேர்வு',
      'darkThemeActive': 'இருண்ட தீம் செயலில்',
      'lightThemeActive': 'ஒளி தீம் செயலில்',
      'liveSessionConnected':
          '🎙️ நேரடி அமர்வு இணைக்கப்பட்டது. பேசத் தொடங்க மைக்ரோஃபோனைத் தட்டவும்.',
      'liveSessionFailed': '❌ நேரடி அமர்வை இணைக்க முடியவில்லை',
      'liveSessionDisconnected': '🔌 நேரடி அமர்வு துண்டிக்கப்பட்டது.',
      'liveSessionError': '❌ நேரடி அமர்வு பிழை',
      'liveSessionNotConnected': 'நேரடி அமர்வு இணைக்கப்படவில்லை',
      'waitForAI': 'AI பேசி முடிக்கும் வரை காத்திருங்கள்',
      'refresh': 'புதுப்பி',
      'messages': 'செய்திகள்',
      'newConversation': 'புதிய உரையாடல்',
      'today': 'இன்று',

      // Obstacle Detector Screen
      'cameraPermissionRequired': 'கேமரா அனுமதி தேவை',
      'cameraPermissionDesc':
          'தடைகளைக் கண்டறிய இந்த பயன்பாட்டிற்கு கேமரா அணுகல் தேவை.',
      'openSettings': 'அமைப்புகளைத் திற',
      'pause': 'இடைநிறுத்து',
      'resume': 'தொடரவும்',
      'pauseDetection': 'கண்டறிதலை இடைநிறுத்து',
      'resumeDetection': 'கண்டறிதலைத் தொடர்',
      'describe': 'விவரி',
      'describeScene': 'காட்சியை விவரி',
      'depthTestReady': 'ஆழச் சோதனை (தயார்)',
      'depthTestNotLoaded': 'ஆழச் சோதனை (ஏற்றப்படவில்லை)',
      'depthTest': 'ஆழ மதிப்பீடு சோதனை',
      'startLiveAssistant': 'நேரடி உதவியாளரைத் தொடங்கு',
      'endLive': 'நேரடியை முடி',
      'live': 'நேரடி',
      'navigate': 'வழிசெலுத்து',
      'navigateButton': 'வழிசெலுத்தலைத் திற',
      'realtimeDetection': 'நிகழ்நேர கண்டறிதல்',
      'detectionActive': 'கண்டறிதல் செயலில்',
      'detectionPaused': 'கண்டறிதல் இடைநிறுத்தப்பட்டது',
      'obstacle': 'தடை',
      'obstacles': 'தடைகள்',
      'labels': 'லேபிள்கள்:',
      'text': 'உரை:',

      // Navigation Screen
      'accessibleNavigation': 'அணுகக்கூடிய வழிசெலுத்தல்',
      'searchDestination': 'இலக்கைத் தேடு...',
      'search': 'தேடு',
      'exploreMode': 'ஆய்வு பயன்முறை - சுற்றுப்புறத்தை தானாக அறிவி',
      'exploringMode': 'ஆய்வு பயன்முறை',
      'stop': 'நிறுத்து',
      'stopNavigation': 'வழிசெலுத்தலை நிறுத்து',
      'retry': 'மீண்டும் முயற்சி',
      'startNavigateTo': 'வழிசெலுத்தலைத் தொடங்கு',
      'repeat': 'மீண்டும்',
      'nextStep': 'அடுத்தது',
      'arrived': 'வந்துவிட்டது',
      'confirm': 'சரி',
      'cancel': 'ரத்துசெய்',
      'nearbyPlaces': 'அருகிலுள்ள இடங்கள் கண்டறியப்பட்டன',
      'locationPermissionRequired': 'இருப்பிட அனுமதி தேவை',
      'locationPermissionDesc':
          'வழிசெலுத்தலைப் பயன்படுத்த அமைப்புகளில் இருப்பிட அனுமதியை இயக்கவும்',
      'locationPermissionDenied': 'இருப்பிட அனுமதி மறுக்கப்பட்டது',
      'locationPermissionPermanentlyDenied':
          'இருப்பிட அனுமதி நிரந்தரமாக மறுக்கப்பட்டது, அமைப்புகளில் இயக்கவும்',
      'gettingLocation': 'இருப்பிடம் பெறப்படுகிறது...',
      'cannotGetLocation': 'தற்போதைய இருப்பிடத்தைப் பெற முடியவில்லை',
      'checkLocationService':
          'இருப்பிட சேவை இயக்கப்பட்டுள்ளதா எனச் சரிபார்க்கவும்',
      'navigationStopped': 'வழிசெலுத்தல் நிறுத்தப்பட்டது',
      'navigationOpened':
          'வழிசெலுத்தல் திறக்கப்பட்டது. இலக்கை உள்ளிடவும் அல்லது ஆய்வு பயன்முறையைத் தொடங்கவும்.',
      'requestingPermission': 'இருப்பிட அனுமதி கோரப்படுகிறது',
      'permissionGranted': 'இருப்பிட அனுமதி வழங்கப்பட்டது',
      'searching': 'தேடுகிறது',
      'noResults': 'முடிவுகள் இல்லை',
      'foundResults': 'முடிவுகள் கிடைத்தன',
      'selected': 'தேர்ந்தெடுக்கப்பட்டது',
      'gettingRoute': 'வழியைப் பெறுகிறது.',

      // Awareness Screen
      'awarenessMenu': 'விழிப்புணர்வு பட்டியல்',
      'visionSimulator': 'பார்வை உருவகப்படுத்தி',
      'sightFacts': 'பார்வை உண்மைகள்',
      'openVisionSimulator': 'பார்வை உருவகப்படுத்தியைத் திற',
      'openSightFacts': 'பார்வை உண்மைகளைத் திற',

      // Vision Simulator Screen
      'normal': 'இயல்பு',
      'slide': 'நகர்த்து',
      'glaucoma': 'கிளாக்கோமா',
      'cataracts': 'கண்புரை',
      'retinopathy': 'விழித்திரை நோய்',
      'selectGlaucoma': 'கிளாக்கோமா பயன்முறையைத் தேர்வு',
      'selectCataracts': 'கண்புரை பயன்முறையைத் தேர்வு',
      'selectRetinopathy': 'விழித்திரை நோய் பயன்முறையைத் தேர்வு',
      'dragToCompare':
          'இயல்பு மற்றும் பாதிக்கப்பட்ட பார்வையை ஒப்பிட நகர்த்தவும்',

      // Sight Facts Screen
      'sightFactsTitle': 'பார்வை உண்மைகள்',
      'nationalSupport': 'தேசிய ஆதரவு (NCBM)',
      'openNationalSupport':
          'மலேசிய தேசிய பார்வையற்றோர் கவுன்சில் இணையதளத்தைத் திற',
      'factOf': '/',
      'fact1Title': 'அமைதியான திருடன்',
      'fact1Content':
          'கிளாக்கோமா பெரும்பாலும் "பார்வையின் அமைதியான திருடன்" என்று அழைக்கப்படுகிறது, ஏனெனில் இது எந்த ஆரம்ப அறிகுறிகளும் வலியும் இல்லாமல் படிப்படியாக பார்வையை திருடுகிறது.',
      'fact2Title': 'சுரங்கப்பாதை பார்வை',
      'fact2Content':
          'முதிர்ந்த கிளாக்கோமா பொதுவாக "சுரங்கப்பாதை பார்வை"க்கு வழிவகுக்கிறது, இதில் நீங்கள் முதலில் உங்கள் பக்க (புற) பார்வையை இழக்கிறீர்கள்.',
      'fact3Title': 'வழக்கமான சோதனைகள்',
      'fact3Content':
          'கிளாக்கோமா மூலம் இழந்த பார்வையை மீட்டெடுக்க முடியாது. அதை முன்கூட்டியே கண்டறிந்து நிறுத்துவதற்கு வழக்கமான கண் பரிசோதனைகள் ஒரே வழி.',
      'fact4Title': 'உள்ளடக்கிய வடிவமைப்பு',
      'fact4Content':
          'உயர் மாறுபாடு பொத்தான்கள் (இந்த பயன்பாட்டில் போல!) குறைந்த பார்வை உள்ளவர்கள் உறுப்புகளை எளிதாக வேறுபடுத்த உதவுகின்றன.',

      // Login Screen
      'login': 'உள்நுழை',
      'register': 'பதிவு செய்',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்து',
      'fullName': 'முழு பெயர்',
      'phoneNumber': 'தொலைபேசி எண்',
      'emergencyContactName': 'அவசர தொடர்பு பெயர்',
      'emergencyContactPhone': 'அவசர தொடர்பு தொலைபேசி',
      'forgotPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'signInWithGoogle': 'Google மூலம் உள்நுழை',
      'orSignInWith': 'அல்லது இதன் மூலம் உள்நுழை',
      'dontHaveAccount': 'கணக்கு இல்லையா?',
      'alreadyHaveAccount': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'registerNow': 'இப்போது பதிவு செய்',
      'loginNow': 'இப்போது உள்நுழை',
      'sendResetEmail': 'மீட்டமைப்பு மின்னஞ்சல் அனுப்பு',
      'backToLogin': 'உள்நுழைவுக்குத் திரும்பு',
      'resetPasswordTitle': 'கடவுச்சொல் மீட்டமைப்பு',
      'resetPasswordDesc':
          'கடவுச்சொல் மீட்டமைப்பு இணைப்பைப் பெற உங்கள் மின்னஞ்சலை உள்ளிடவும்.',
      'verifyEmail': 'உங்கள் மின்னஞ்சலை சரிபார்க்கவும்',
      'verifyEmailDesc':
          'சரிபார்ப்பு மின்னஞ்சல் அனுப்பப்பட்டது. உங்கள் இன்பாக்ஸைச் சரிபார்த்து உங்கள் மின்னஞ்சலை சரிபார்க்கவும்.',
      'resendEmail': 'மீண்டும் அனுப்பு',
      'checkVerification': 'நான் சரிபார்த்தேன்',
      'personalInfo': 'தனிப்பட்ட தகவல்',
      'emergencyContact': 'அவசர தொடர்பு',
      'accountInfo': 'கணக்கு தகவல்',

      // Emergency / Fall Detection
      'fallDetected': 'வீழ்ச்சி கண்டறியப்பட்டது!',
      'callingAssistance': 'உதவியை அழைக்கிறது:',
      'imOkay': 'நான் நலம்',
      'cancelAlarm': '(எச்சரிக்கையை ரத்துசெய்)',
      'imOkayButton': 'நான் நலம், அவசர எச்சரிக்கையை ரத்துசெய்',

      // Additional Login Keys
      'signIn': 'உள்நுழை',
      'createAccount': 'கணக்கை உருவாக்கு',
      'dontHaveAccountRegister': 'கணக்கு இல்லையா? இங்கே பதிவு செய்யவும்',
      'forgotPasswordResetHere':
          'கடவுச்சொல் மறந்துவிட்டதா? இங்கே மீட்டமைக்கவும்',
      'continueWithGoogle': 'Google மூலம் தொடரவும்',
      'or': 'அல்லது',
      'createYourAccount': 'உங்கள் கணக்கை உருவாக்கவும்',
      'fillInDetails': 'தொடங்க உங்கள் விவரங்களை நிரப்பவும்',
      'setPassword': 'கடவுச்சொல்லை அமை',
      'passwordHint': 'குறைந்தது 6 எழுத்துகள், 1 பெரிய எழுத்து, 1 எண்',
      'emergencyContactDesc':
          'பயன்பாட்டால் அவசர நிலைமைகள் கண்டறியப்பட்டால் இந்த நபர் தொடர்பு கொள்ளப்படுவார்.',
      'alreadyHaveAccountSignIn': 'ஏற்கனவே கணக்கு உள்ளதா? இங்கே உள்நுழையவும்',
      'verificationEmailSent':
          'சரிபார்ப்பு மின்னஞ்சல் அனுப்பப்பட்டது! இன்பாக்ஸைச் சரிபார்க்கவும்.',
      'checkYourEmail': 'உங்கள் மின்னஞ்சலைச் சரிபார்க்கவும்',
      'verificationLinkSent': 'சரிபார்ப்பு இணைப்பை நாங்கள் அனுப்பியுள்ளோம்',
      'clickLinkToVerify':
          'உங்கள் கணக்கைச் சரிபார்க்க மின்னஞ்சலில் உள்ள இணைப்பைக் கிளிக் செய்யவும்.',
      'iveVerifiedMyEmail': 'நான் மின்னஞ்சலைச் சரிபார்த்தேன்',
      'resendVerificationEmail': 'சரிபார்ப்பு மின்னஞ்சலை மீண்டும் அனுப்பு',
      'emailNotVerified':
          'மின்னஞ்சல் இன்னும் சரிபார்க்கப்படவில்லை. இன்பாக்ஸைச் சரிபார்த்து இணைப்பைக் கிளிக் செய்யவும்.',
      'resetLinkSent': 'மீட்டமைப்பு இணைப்பு அனுப்பப்பட்டது!',
      'resetLinkSentDesc':
          'உங்கள் இன்பாக்ஸைச் சரிபார்த்து கடவுச்சொல்லை மீட்டமைக்க இணைப்பைக் கிளிக் செய்யவும்.',
      'tryDifferentEmail': 'வேறு மின்னஞ்சலை முயற்சிக்கவும்',
      'forgotYourPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'forgotYourPasswordDesc':
          'உங்கள் கணக்குடன் தொடர்புடைய மின்னஞ்சல் முகவரியை உள்ளிடவும், கடவுச்சொல் மீட்டமைப்பு இணைப்பை அனுப்புவோம்.',
      'sendResetLink': 'மீட்டமைப்பு இணைப்பை அனுப்பு',
      'emailAddress': 'மின்னஞ்சல் முகவரி',
      'normalVision': 'இயல்பு',
      'emailHint': 'எ.கா. john@example.com',
      'nameHint': 'எ.கா. குமார்',
      'phoneHint': 'எ.கா. +60123456789',
      'fullNameRequired': 'முழு பெயர் *',
      'emailRequired': 'மின்னஞ்சல் முகவரி *',
      // Profile Feature
      'profileTitle': 'பயனர் சுயவிவரம்',
      'openingProfile': 'பயனர் சுயவிவரத்தைத் திறக்கிறது',
      'updateProfile': 'மாற்றங்களை சேமிக்கவும்',
      'profileUpdated': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      'updateFailed': 'சுயவிவரத்தைப் புதுப்பிப்பதில் தோல்வி',
      'phoneRequired': 'தொலைபேசி எண் *',
      'passwordRequired': 'கடவுச்சொல் *',
      'confirmPasswordRequired': 'கடவுச்சொல்லை உறுதிப்படுத்து *',
      'emergencyContactNameRequired': 'அவசர தொடர்பு பெயர் *',
      'emergencyContactPhoneRequired': 'அவசர தொடர்பு தொலைபேசி *',
      'emergencyPhoneHint': 'எ.கா. +60198765432',
      'verificationResent':
          'சரிபார்ப்பு மின்னஞ்சல் மீண்டும் அனுப்பப்பட்டது! இன்பாக்ஸைச் சரிபார்க்கவும்.',
      'weSentResetLink':
          'கடவுச்சொல் மீட்டமைப்பு இணைப்பை நாங்கள் அனுப்பியுள்ளோம்',

      // Obstacle Detector Hub
      'obstacleDetectorHub': 'தடை கண்டறிதல்',
      'chooseAFeature': 'ஒரு அம்சத்தைத் தேர்ந்தெடுக்கவும்',
      'objectDetection': 'பொருள் கண்டறிதல்',
      'objectDetectionSubtitle':
          'கேமரா மற்றும் ஹாப்டிக் பின்னூட்டத்துடன் தடைகளைக் கண்டறியவும்',
      'objectDetectionSemantic':
          'பொருள் கண்டறிதல். ஹாப்டிக் மற்றும் குரல் பின்னூட்டத்துடன் கேமராவைப் பயன்படுத்தி தடைகளைக் கண்டறியவும்.',
      'openingObjectDetection': 'பொருள் கண்டறிதலைத் திறக்கிறது',
      'liveAssistant': 'நேரடி',
      'liveAssistantSubtitle': 'குரல் மற்றும் கேமராவுடன் நிகழ்நேர AI உதவியாளர்',
      'liveAssistantSemantic':
          'நேரடி உதவியாளர். குரல் மற்றும் கேமராவைப் பயன்படுத்தி Gemini AI உடன் நிகழ்நேர உரையாடலைத் தொடங்கவும்.',
      'openingLiveAssistant': 'நேரடி உதவியாளரைத் திறக்கிறது',
      'liveTest': 'நேரடி சோதனை',
      'liveTestSubtitle': 'படிப்படியாக நேரடி API-ஐ பிழைத்திருத்தம் செய்யவும்',
      'liveTestSemantic':
          'நேரடி சோதனை. படிப்படியாக Gemini Live API-ஐ பிழைத்திருத்தம் செய்யவும்.',
      'openingLiveTest': 'நேரடி சோதனையைத் திறக்கிறது',
      'navigateSubtitle': 'குரல் வழிகாட்டும் நடைபயணத் திசைகள்',
      'navigateSemantic':
          'வழிகாட்டுதல். இலக்குக்கான குரல் வழிகாட்டும் நடைபயணத் திசைகளைப் பெறுங்கள்.',
      'openingNavigation': 'வழிகாட்டுதலைத் திறக்கிறது',
      'goBackHome': 'முகப்புத் திரைக்குத் திரும்பு',
      'obstacleDetectorMenuTts':
          'தடை கண்டறிதல் மெனு. மூன்று விருப்பங்கள் கிடைக்கின்றன: பொருள் கண்டறிதல், நேரடி உதவியாளர், மற்றும் வழிகாட்டுதல்.',

      // Feature & Settings TTS
      'usingLanguage': 'நீங்கள் தமிழ் பயன்படுத்துகிறீர்கள்',
      'usingDarkMode': 'இருண்ட பயன்முறையைப் பயன்படுத்துகிறது',
      'usingLightMode': 'ஒளி பயன்முறையைப் பயன்படுத்துகிறது',
      'textSizeChanged': 'உரை அளவு மாற்றப்பட்டுள்ளது ',
      'speechSpeedChanged': 'பேச்சு வேகம் மாற்றப்பட்டுள்ளது ',
      'hapticEnabled': 'தொடு பின்னூட்டம் இயக்கப்பட்டது',
      'hapticDisabled': 'தொடு பின்னூட்டம் முடக்கப்பட்டது',
      'voiceGuidance': 'குரல் வழிகாட்டல்',
      'voiceGuidanceEnabled': 'குரல் வழிகாட்டல் இயக்கப்பட்டுள்ளது',
      'voiceGuidanceDisabled': 'குரல் வழிகாட்டல் முடக்கப்பட்டுள்ளது',
      'openingChatbot': 'AI அரட்டையைத் திறக்கிறது',
      'openingVisionAwareness': 'பார்வை விழிப்புணர்வைத் திறக்கிறது',
      'openingSettings': 'அமைப்புகளைத் திறக்கிறது',
      'openingObstacleDetection': 'தடை கண்டறிதலைத் திறக்கிறது',
    },
  };

  String get(String key) {
    return _values[languageCode]?[key] ?? _values['en']?[key] ?? key;
  }
}
